### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by anshumanv** [anshumanv/ongaku-react#1]

**Comment by deveshd2k** [comment]
I can help in adding CONTRIBUTING.md if you can tell me what to add.

**Comment by anshumanv** [comment]
Hey @deveshd2k thanks for considering a contribution here, unfortunately I've already opened up a PR in #2 , you can suggest any changes if needed there or you can send a PR later to enhance it.

**Comment by filoxo** [comment]
LGTM!
