### ISSUE TITLE
Disabling all preferences may crash app

### ISSUE THREAD

**Issue by filoxo** [anshumanv/ongaku-react#11]
Currently, disabling all preferences and attempting to play another song (next or prev) will crash the app since the array of track data is now totally empty.

Probably should guard against this by either preventing the last "enabled" option from being disabled if the other 2 are disabled, or by reenabling the first option if all of them are disabled.

**Comment by anshumanv** [comment]
Let's go with the first workaround, The last option will be uneditable if it's the only enabled option left.
