### ISSUE TITLE
Clicking over individual list items on Playlist should transition to that track.

### ISSUE THREAD

**Issue by anshumanv** [anshumanv/ongaku-react#28]

**Comment by anshumanv** [comment]
@filoxo what could be the ideal approach for this?
All list items have a key prop which is the name of the song, I can get that name and search for the object that matches the key through the data array in the state?

**Comment by filoxo** [comment]
This is a little tricky. The simplest way would be to simply use the array index as the identifier, but that would easily break if an item were removed or placed somewhere else. Using the name to search through all objects in the array is pretty costly; O(n) if you use `findIndex`, I think.

At that point, you might then introduce some sort of faster sorting algorithm, or a lookup table. Or copy the values into another array that saved to localStorage or something. Honestly, this is kinda just spitballing, do any of these options sound like what you'd want to implement?
